#
###################################
# Site wide configuration
####################################
#
title: Hamidreza Moradi
email: Hamid@europe.com
description: Hamid Live CV
url: https://irnb.github.com/whoami # the base hostname & protocol for your site
keywords: ["Hamidreza Moradi","Hamidreza Moradi khanghah", "Moradi" ,"Blockchain", "Solidity", "Bitcoin", "Ethereum", "DeFi", "Decentralization", "researcher"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Hamidreza Moradi
  avatar: Hamid.jpg
  job: "Blockchain Researcher / Computer Science student"
  bio: "Based in Tehran, IR."
  email: hamid@europe.com
  #disqus-shortname: renyuanzblog
  twitter: newbateni2 #username
  facebook: #username
  bing-verify:
  github: irnb #username
  linkedin: hamidreza-moradi-2b07581a7 #username
  xing: #username
  instagram: newbateni
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  blog: http://irnb.github.io/
